# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xz2yYJOTk46kGTBbwnAWbmYG6v-yz4xs
"""

!pip install torch transformers

from transformers import pipeline
import re
import datetime

llm = pipeline(
    "text2text-generation",
    model="google/flan-t5-large",
    max_length=128
)

print("AI Agent is running (type 'exit' to quit)")

def calculator_tool(text):
    try:
        expression = re.findall(r"[0-9]+|[\+\-\*/]", text)
        return str(eval("".join(expression)))
    except:
        return "Unable to calculate."

def time_tool():
    return datetime.datetime.now().strftime("%d-%m-%Y %H:%M:%S")

def chat_tool(user_input):
    prompt = f"""
You are a helpful AI assistant.
Answer clearly in simple language.

User: {user_input}
Assistant:
"""
    return llm(prompt)[0]["generated_text"].strip()

def decide_and_act(user_input):
    text = user_input.lower()

    
    if any(op in text for op in ["+", "-", "*", "/"]):
        return calculator_tool(user_input)

    if "time" in text or "date" in text:
        return time_tool()

    
    return chat_tool(user_input)

while True:
    user_input = input("You: ")

    if user_input.lower() == "exit":
        print("Agent: Goodbye!")
        break

    result = decide_and_act(user_input)
    print("Agent:", result)
